// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KUQZhEnR6sWUvqkStS65NqGqMg0DYa0',
    appId: '1:1080728350143:web:06460f77f577fd92f7050a',
    messagingSenderId: '1080728350143',
    projectId: 'to-do-list-app-2ed21',
    authDomain: 'to-do-list-app-2ed21.firebaseapp.com',
    storageBucket: 'to-do-list-app-2ed21.firebasestorage.app',
    measurementId: 'G-YPBSZ8797P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOsx1VwNW-CH_PzBomOE-3bQIA7qjh1A',
    appId: '1:1080728350143:ios:a49eb41227e4b733f7050a',
    messagingSenderId: '1080728350143',
    projectId: 'to-do-list-app-2ed21',
    storageBucket: 'to-do-list-app-2ed21.firebasestorage.app',
    iosBundleId: 'com.example.todoapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOsx1VwNW-CH_PzBomOE-3bQIA7qjh1A',
    appId: '1:1080728350143:ios:a49eb41227e4b733f7050a',
    messagingSenderId: '1080728350143',
    projectId: 'to-do-list-app-2ed21',
    storageBucket: 'to-do-list-app-2ed21.firebasestorage.app',
    iosBundleId: 'com.example.todoapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-KUQZhEnR6sWUvqkStS65NqGqMg0DYa0',
    appId: '1:1080728350143:web:b3b806f7a2dc57d9f7050a',
    messagingSenderId: '1080728350143',
    projectId: 'to-do-list-app-2ed21',
    authDomain: 'to-do-list-app-2ed21.firebaseapp.com',
    storageBucket: 'to-do-list-app-2ed21.firebasestorage.app',
    measurementId: 'G-2JBFKZTZ61',
  );
}
