// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrdYabhIXE_EKmkHULMQgJoBEwJwnXow',
    appId: '1:614187393450:web:01dcd4704c563290520bd3',
    messagingSenderId: '614187393450',
    projectId: 'trip-destination-app',
    authDomain: 'trip-destination-app.firebaseapp.com',
    storageBucket: 'trip-destination-app.firebasestorage.app',
    measurementId: 'G-R34ZSXQ41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PsDNKyEBsMWJw8-6MZU7ExXQlKbYQsk',
    appId: '1:614187393450:android:e97ecef7d38aebff520bd3',
    messagingSenderId: '614187393450',
    projectId: 'trip-destination-app',
    storageBucket: 'trip-destination-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6nra72uR71qyeP4LrQ4UBibyeM8a2gY',
    appId: '1:614187393450:ios:5136bdd612464852520bd3',
    messagingSenderId: '614187393450',
    projectId: 'trip-destination-app',
    storageBucket: 'trip-destination-app.firebasestorage.app',
    iosBundleId: 'com.example.tripdestinationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXrdYabhIXE_EKmkHULMQgJoBEwJwnXow',
    appId: '1:614187393450:web:43015c56ea9350f9520bd3',
    messagingSenderId: '614187393450',
    projectId: 'trip-destination-app',
    authDomain: 'trip-destination-app.firebaseapp.com',
    storageBucket: 'trip-destination-app.firebasestorage.app',
    measurementId: 'G-WHK7XJYEVZ',
  );
}
